In [2]:
import numpy as np

## 合并拆分操作

In [15]:
d1 = np.random.normal(1,1,size=(10))
d2 = d1 * 2

[ 2.16091506  0.36730287  3.43022995 -0.43568811  0.09806673  1.7779166
  4.28797026  2.36804073 -0.30665091  2.38455926]


In [16]:
d1

array([ 1.08045753,  0.18365144,  1.71511498, -0.21784406,  0.04903336,
        0.8889583 ,  2.14398513,  1.18402036, -0.15332546,  1.19227963])

In [17]:
d2

array([ 2.16091506,  0.36730287,  3.43022995, -0.43568811,  0.09806673,
        1.7779166 ,  4.28797026,  2.36804073, -0.30665091,  2.38455926])

In [41]:
# 将两个1维数组合并, axis 按行或列进行拼接
# concatenate 只适用于维度匹配的矩阵
z = np.concatenate([d1,d2])
w = np.concatenate([[z,z],[z * 2, z*2]], axis=1)

array([[ 1.08045753,  0.18365144,  1.71511498, -0.21784406,  0.04903336,
         0.8889583 ,  2.14398513,  1.18402036, -0.15332546,  1.19227963,
         2.16091506,  0.36730287,  3.43022995, -0.43568811,  0.09806673,
         1.7779166 ,  4.28797026,  2.36804073, -0.30665091,  2.38455926,
         2.16091506,  0.36730287,  3.43022995, -0.43568811,  0.09806673,
         1.7779166 ,  4.28797026,  2.36804073, -0.30665091,  2.38455926,
         4.32183012,  0.73460574,  6.86045991, -0.87137622,  0.19613345,
         3.55583319,  8.57594053,  4.73608146, -0.61330182,  4.76911853],
       [ 1.08045753,  0.18365144,  1.71511498, -0.21784406,  0.04903336,
         0.8889583 ,  2.14398513,  1.18402036, -0.15332546,  1.19227963,
         2.16091506,  0.36730287,  3.43022995, -0.43568811,  0.09806673,
         1.7779166 ,  4.28797026,  2.36804073, -0.30665091,  2.38455926,
         2.16091506,  0.36730287,  3.43022995, -0.43568811,  0.09806673,
         1.7779166 ,  4.28797026,  2.36804073, -0.

In [55]:
# np.vstack/hstack 容错性更好的 垂直合并
np.hstack([z,np.zeros(shape=(20))])

array([ 1.08045753,  0.18365144,  1.71511498, -0.21784406,  0.04903336,
        0.8889583 ,  2.14398513,  1.18402036, -0.15332546,  1.19227963,
        2.16091506,  0.36730287,  3.43022995, -0.43568811,  0.09806673,
        1.7779166 ,  4.28797026,  2.36804073, -0.30665091,  2.38455926,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

In [70]:
# np.vsplit/h.split : 在垂直和水平进行分割
c1,c2,others = np.hsplit(w,[1,2])
others

array([[ 1.71511498, -0.21784406,  0.04903336,  0.8889583 ,  2.14398513,
         1.18402036, -0.15332546,  1.19227963,  2.16091506,  0.36730287,
         3.43022995, -0.43568811,  0.09806673,  1.7779166 ,  4.28797026,
         2.36804073, -0.30665091,  2.38455926,  2.16091506,  0.36730287,
         3.43022995, -0.43568811,  0.09806673,  1.7779166 ,  4.28797026,
         2.36804073, -0.30665091,  2.38455926,  4.32183012,  0.73460574,
         6.86045991, -0.87137622,  0.19613345,  3.55583319,  8.57594053,
         4.73608146, -0.61330182,  4.76911853],
       [ 1.71511498, -0.21784406,  0.04903336,  0.8889583 ,  2.14398513,
         1.18402036, -0.15332546,  1.19227963,  2.16091506,  0.36730287,
         3.43022995, -0.43568811,  0.09806673,  1.7779166 ,  4.28797026,
         2.36804073, -0.30665091,  2.38455926,  2.16091506,  0.36730287,
         3.43022995, -0.43568811,  0.09806673,  1.7779166 ,  4.28797026,
         2.36804073, -0.30665091,  2.38455926,  4.32183012,  0.73460574,
   

## 矩阵运算

In [125]:
# Uninversal Function
n = 10
L = [_ for _ in range(n)]
A = np.array(L)
np.log(A+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [149]:
# 矩阵乘法
a = np.full((2,2),1)
b = np.full((2,2),12)
a.dot(b)

array([[24, 24],
       [24, 24]])

In [148]:
# 向量和矩阵运算
v = np.array([1,2])
a + np.vstack([v] * a.shape[0])

array([[2, 3],
       [2, 3]])

In [ ]:
# 矩阵的逆 - 方阵可求逆
a = np.random.normal(1,1,(5,5))
a.dot(np.linalg.inv(a))

## 聚合运算

In [235]:
%%time
a.sum(axis=1)

CPU times: user 30 µs, sys: 1e+03 ns, total: 31 µs
Wall time: 34.8 µs


array([6.95789082, 5.36857111, 5.36010256, 6.96525016, 6.67028485])

In [238]:
np.prod(a, axis=0)

array([ 3.39919095e-04,  2.55684995e+01, -1.39673864e-01,  6.26407367e+00,
        3.75010098e-01])

In [247]:
np.median(a)

1.0405568279417576

In [256]:
# 百分位数，0 25 50 75 100 约定多少
np.percentile(a, q=50) # 这组数中，百分之多少的数据小于返回的数

1.0405568279417576

In [ ]:
np.var(np.random.normal(0,1,1000))

## Numpy 索引

In [11]:
# argument 返回固定数值的索引

import numpy as np
data = np.random.normal(0,1000,size=500)
data.argmin()

21

In [57]:
# 排序和使用索引, arg, arg
np.random.shuffle(data.reshape((5,-1)))
np.sort(data, axis=0)
print(data)

# argsort
np.argsort(data)

np.partition(data,0)

[-6.34512409e+02  1.42266136e+03 -1.87966191e+03  2.35763333e+03
 -1.76812466e+03 -6.48550747e+02  1.45516904e+03 -8.97556686e+02
  2.65784830e+02 -1.06123679e+03  8.86996610e+02  3.99123114e+02
  1.93221632e+03 -1.32004146e+03  2.77562091e+02  1.68206278e+03
 -1.46122055e+02 -5.58760271e+02  3.30899009e+02  1.59222116e+03
 -8.21641683e+02  1.21176526e+03  3.32851335e+02  1.46992448e+01
  2.38998270e+02  5.53669222e+02 -3.92669442e+02 -4.02996583e+02
 -7.71595925e+02 -3.81140929e+02 -3.59181809e+02 -1.15355438e+02
  1.48244214e+03 -4.13667867e+02  1.29147853e+03 -9.22689044e+02
  1.77201962e+03  1.41734158e+03 -9.01524289e+02 -9.67226675e+02
 -3.93401178e+01 -2.48118271e+02  4.78426061e+02  2.25666388e+02
 -1.04580255e+02 -9.69390104e+02 -8.91537555e+02 -2.07431356e+03
  9.18839079e+02 -5.89576211e+02 -1.09735972e+03  5.07229228e+02
 -5.97602012e+02  4.27481171e+02  1.77193963e+02 -7.54452494e+02
 -1.46011688e+03  1.14414007e+03  4.19305595e+02  7.19145589e+02
 -2.36529404e+02 -6.02829

array([-3.33137491e+03,  1.42266136e+03, -1.87966191e+03,  2.35763333e+03,
       -1.76812466e+03, -6.48550747e+02,  1.45516904e+03, -8.97556686e+02,
        2.65784830e+02, -1.06123679e+03,  8.86996610e+02,  3.99123114e+02,
        1.93221632e+03, -1.32004146e+03,  2.77562091e+02,  1.68206278e+03,
       -1.46122055e+02, -5.58760271e+02,  3.30899009e+02,  1.59222116e+03,
       -8.21641683e+02,  1.21176526e+03,  3.32851335e+02,  1.46992448e+01,
        2.38998270e+02,  5.53669222e+02, -3.92669442e+02, -4.02996583e+02,
       -7.71595925e+02, -3.81140929e+02, -3.59181809e+02, -1.15355438e+02,
        1.48244214e+03, -4.13667867e+02,  1.29147853e+03, -9.22689044e+02,
        1.77201962e+03,  1.41734158e+03, -9.01524289e+02, -9.67226675e+02,
       -3.93401178e+01, -2.48118271e+02,  4.78426061e+02,  2.25666388e+02,
       -1.04580255e+02, -9.69390104e+02, -8.91537555e+02, -2.07431356e+03,
        9.18839079e+02, -5.89576211e+02, -1.09735972e+03,  5.07229228e+02,
       -5.97602012e+02,  

## Fancying Indexing

In [13]:
import numpy as np

# 制定索引，再传入查询到具体数值
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
cc = [1,0,1,1,1]
x[0:2,[True,False,False,False]]

array([[0],
       [4]])